In [ ]:
import pandas as pd
bucket = [3.14, 'pi', 2.718]
series = pd.Series(bucket)
print(series)

0     3.14
1       pi
2    2.718
dtype: object

In [ ]:
import pandas as pd
items = { 'col1' : [1,2,3], 'col2' : [3,4,5]}
df_from_dict =  pd.DataFrame(items)
print(df_from_dict)

   col1  col2
0     1     3
1     2     4
2     3     5

In [ ]:
'''import pandas as pd
df = pd.read_csv('data.csv')
print(df.head)'''

In [ ]:
'''
import pandas as pd
df = pd.read_csv('data.csv' , delimiter = ';')
print(df.head())

In [ ]:
'''import pandas as pd
df = pd.read_csv('data.csv')
value = df.iloc[3,4]
print(value)

In [ ]:
'''import pandas as pd
df = pd.read_csv('data.csv')
age_filtered = df['Age'] > 23
result = df[age_filtered]
print(result)

In [ ]:
'''import pandas as pd
df = pd.read_csv('data.csv')
mean = df['Age'].mean()
print(mean)

In [ ]:
'''import pandas as pd
df = pd.read_csv('data.csv')
min_amount = df['Credit amount'].min()
print(min_amount)

In [ ]:
'''import pandas as pd
df = pd.read_csv('data.csv')
group = df.groupby('Sex')
min_age = group['Age'].min()
print(min_age)

In [ ]:
'''import pandas as pd
df = pd.read_csv('data.csv')
merged = pd.merge(df,df,on='Sex',how='inner')
print(merged)

In [ ]:
import numpy as np

sales_data = [200, 450, 150, 400, 500, 700]

# Write your code below
sales_array = np.array(sales_data)
min_index = np.argmin(sales_array)
max_index= np.argmax(sales_array)
print(min_index)
print(max_index)

2
5

In [ ]:
import numpy as np

# Write your code below
sales_data = [100,150,200,250,300]
new_sale = 350
updated_sales_data= np.append(sales_data, new_sale)
print(updated_sales_data)

[100 150 200 250 300 350]

In [ ]:
import numpy as np

# Write your code below
team_a_scores = np.array([80,85,90,95,100])
team_b_scores = np.array([70,75,80,85,90])
all_team_scores = np.concatenate((team_a_scores, team_b_scores))
print(all_team_scores)

[ 80  85  90  95 100  70  75  80  85  90]

In [ ]:
import numpy as np

# Write your code below
daily_temperatures = np.array([72,75,78,70,68])
total_temperature = np.sum(daily_temperatures)
print(total_temperature)

363

In [ ]:
import numpy as np

# Write your code below
exam_scores = ([85,90,88,92,87])
average_score = np.mean(exam_scores)
print(average_score)

88.4

In [ ]:
import numpy as np

# Write your code below
age_data = ([25,30,35,40,45])
median_age = np.median(age_data)
print(median_age)

35.0

In [ ]:
import numpy as np

# Write your code below
sales_data = [150,200,250,300,350]
array = np.array(sales_data)
sliced_array = array[1:4]
print(sliced_array)

[200 250 300]

In [ ]:
import numpy as np
demo_array = np.arange(0,10)
demo_array<3

array([ True,  True,  True, False, False, False, False, False, False,
       False])

In [ ]:
import pandas as pd
flowers = pd.Series([2, 3, 5, 4], index=['lily', 'rose', 'daisy', 'lotus'])
flowers['daisy']
print(flowers)

lily     2
rose     3
daisy    5
lotus    4
dtype: int64


customer	category	important	sales
0	101	cat2	yes 	123
1	102	cat2	no 	52
2	103	cat1	yes 	214
3	104	cat3	yes	663

In [ ]:
import numpy as np
ab = np.array([1,10,21,35,72])
print(ab)

[ 1 10 21 35 72]

In [ ]:
import numpy as np
ab = np.array([[9,8,7],[6,5,4],[3,2,1]])
cd = np.arange(start=1, stop=10, step=1).reshape(3,3)
print(cd)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

In [ ]:
import numpy as np
mat = np.matrix([[ 1, 4, 9, 121, 144, 169],
                [ 16, 25, 36, 196, 225, 256],
                [ 49, 64, 81, 289, 324, 361]])
mat_aver = mat.mean()
print(mat_aver)

131.66666666666666

In [ ]:
import numpy as np
a = np.arange(0,20)
print(a[2:7])

[2 3 4 5 6]

In [ ]:
import numpy as np
ab = np.cos([0, 1, 2, 3, 4])
print(ab)

[ 1.          0.54030231 -0.41614684 -0.9899925  -0.65364362]

In [ ]:
import numpy as np
list_1 = [1,2,3]
list_2 = [4,5,6]
new_list = list_1 + list_2
print(new_list)
array_1 = np.array([1,2,3])
array_2 = np.array([4,5,6])
new_array = array_1 + array_2
print(new_array)

[1, 2, 3, 4, 5, 6]
[5 7 9]

In [ ]:
import numpy as np
mat = np.array([[1, 2, 1], [4, 5, 9],[1, 8, 9]])
mat[1] = 5
print(mat)

[[1 2 1]
 [5 5 5]
 [1 8 9]]

In [ ]:
import numpy as np
array_1 = np.array([1, 2, 3, 5, 8])
array_2 = np.array([0, 3, 4, 2, 1])
new_array = array_1+ array_2
final_array = new_array*array_1
print(final_array[2])

21

In [ ]:
import numpy as np
ab = np.identity(2*2)
print(ab)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

In [ ]:
import numpy as np
ab = np.identity(2)
print(ab)

[[1. 0.]
 [0. 1.]]

In [ ]:
import numpy as np
ab = np.ones((2,2))
print(ab)

[[1. 1.]
 [1. 1.]]

In [ ]:
import numpy as np
n1 = np.matrix([[121, 144, 169], [196, 225, 256], [ 289, 324, 361]])
n2 = np.matrix([[ 1, 4, 9], [ 1, 5, 4], [ 9, 4, 8]])
dot_prod = np.dot(n1,n2)
print(dot_prod)

[[1786 1880 3017]
 [2725 2933 4712]
 [3862 4220 6785]]

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import pandas as pd
df = pd.read_csv('/content/drive/MyDrive/books.csv')
print(df)

                                                  title  \
0                           The Hunchback of Notre-Dame
1     La Cucina Di Lidia: Recipes and Memories from ...
2                                     Breach of Promise
3                     Brief Interviews with Hideous Men
4     The Killing Dance (Anita Blake  Vampire Hunter...
...                                                 ...
4995                                 The Complete Works
4996                               Shipwreck (Island I)
4997           Every Night Italian: Every Night Italian
4998                                     Go Down  Moses
4999  The Avignon Quintet: Monsieur  Livia  Constanc...

                           author  average_rating         isbn13  \
0                     Victor Hugo            4.00  9780345472427
1     Lidia Matticchio Bastianich            4.14  9780767914222
2                James Scott Bell            4.00  9780310243878
3            David Foster Wallace            3.86  9780349111889
4             Laurell K. Hamilton            4.13  9780425209066
...                           ...             ...            ...
4995          Michel de Montaigne            4.44  9781400040216
4996                Gordon Korman            3.80  9780439023313
4997               Giuliano Hazan            3.79  9780684800288
4998             William Faulkner            3.93  9780679732174
4999             Lawrence Durrell            4.07  9780571225552

     language_code  num_pages  ratings_count  text_reviews_count  \
0            en-US      534.0            140                  22
1            en-GB      288.0             48                   3
2              eng      345.0            368                  36
3              eng      273.0          18335                1155
4            en-US      368.0          59524                 946
...            ...        ...            ...                 ...
4995           eng     1392.0            166                  13
4996           eng        NaN            103                  14
4997           eng      256.0             70                   2
4998           eng      365.0           8289                 370
4999         en-US     1376.0            287                  23

                   publisher  year
0             Modern Library  2004
1            Clarkson Potter  2003
2                  Zondervan  2004
3                     Abacus  2000
4          Berkley Hardcover  2006
...                      ...   ...
4995      Everyman's Library  2003
4996  Scholastic Audio Books  2007
4997                Scribner  2000
4998                 Vintage  1991
4999           Faber & Faber  2004

[5000 rows x 10 columns]

In [ ]:
print(df.head())

                                               title  \
0                        The Hunchback of Notre-Dame
1  La Cucina Di Lidia: Recipes and Memories from ...
2                                  Breach of Promise
3                  Brief Interviews with Hideous Men
4  The Killing Dance (Anita Blake  Vampire Hunter...

                        author  average_rating         isbn13 language_code  \
0                  Victor Hugo            4.00  9780345472427         en-US
1  Lidia Matticchio Bastianich            4.14  9780767914222         en-GB
2             James Scott Bell            4.00  9780310243878           eng
3         David Foster Wallace            3.86  9780349111889           eng
4          Laurell K. Hamilton            4.13  9780425209066         en-US

   num_pages  ratings_count  text_reviews_count          publisher  year
0      534.0            140                  22     Modern Library  2004
1      288.0             48                   3    Clarkson Potter  2003
2      345.0            368                  36          Zondervan  2004
3      273.0          18335                1155             Abacus  2000
4      368.0          59524                 946  Berkley Hardcover  2006

In [ ]:
dimensions = df.shape
print(dimensions)

(5000, 10)

In [ ]:
df.describe()

,average_rating,isbn13,num_pages,ratings_count,text_reviews_count,year
count,5000.000000,5.000000e+03,4967.000000,5.000000e+03,5000.000000,5000.000000
mean,3.931932,9.752758e+12,341.094021,2.017549e+04,592.688600,2000.131800
std,0.348741,5.129254e+11,230.986115,1.175026e+05,2539.539004,8.069043
min,0.000000,8.987060e+09,1.000000,0.000000e+00,0.000000,1913.000000
25%,3.770000,9.780345e+12,200.000000,1.050000e+02,9.000000,1998.000000
50%,3.960000,9.780571e+12,304.000000,7.915000e+02,49.000000,2003.000000
75%,4.140000,9.780871e+12,416.500000,5.348750e+03,249.000000,2005.000000
max,5.000000,9.789879e+12,3342.000000,2.457092e+06,55843.000000,2019.000000

In [ ]:
object_count = (df.dtypes == 'object').sum()
print(object_count)

4

In [ ]:
count = (df['average_rating'] > 4).sum()
print(f"Total books with a rating > 4: {count}")

Total books with a rating > 4: 2115

In [ ]:
hidden_gems = df[(df['average_rating'] > 4.5) & (df['ratings_count'] < 10)]
print(hidden_gems)

                                                  title  \
63                                             鋼之鍊金術師 9
178                                            鋼之鍊金術師 6
224                             Stargirl LitPlans on CD
454   Literature Circle Guide: Bridge to Terabithia:...
584                       Falling Angels (Luc Actar #1)
681        Fanning the Flame: Bible  Cross  and Mission
696                  Tyrannosaurus Wrecks (Stanley  #1)
741   The John Deere Two-Cylinder Tractor Encycloped...
757   The American Campaign: U.S. Presidential Campa...
1837  The Goon Show  Volume 4: My Knees Have Fallen ...
1856                                          鋼之鍊金術師 10
1960  Wissenschaft der Logik: Die Lehre Vom Begriff ...
2244  Getting a Grip on the Basics: Building a Firm ...
2496                               Come Away My Beloved
3178  Organizational Architecture: Designs for Chang...
3438         Bill Gates: Computer Legend (Famous Lives)
3706  A Wife After God's Own Heart Growth and Study ...
3833  His Princess Devotional: A Royal Encounter Wit...
3909                 Little Big Book for God's Children
3927  Colossians and Philemon: A Critical and Exeget...
4108                  Willem de Kooning: Late Paintings
4415                                           Corvette
4455  The Complete Theory Fun Factory: Music Theory ...
4917                          Taxation of Mineral Rents
4933  Oliver Wendell Holmes in Paris: Medicine  Theo...

                             author  average_rating         isbn13  \
63                   Hiromu Arakawa            4.57  9789861156521
178                  Hiromu Arakawa            4.58  9789861146140
224                 Mary B. Collins            4.86  9781583372920
454                  Tara MacCarthy            5.00  9780439271714
584               Melissa M. Garcia            4.67  9780595377107
681                  Chris    Green            5.00  9780310249870
696                  Laura Driscoll            5.00  9780786845033
741                   Don Macmillan            4.75  9780760329634
757               James E. Campbell            5.00  9780890969403
1837                     NOT A BOOK            5.00  9780563388692
1856                 Hiromu Arakawa            4.60  9789861156538
1960  Georg Wilhelm Friedrich Hegel            4.78  9783787307678
2244                  Beth A. Jones            4.67  9781577948261
2496             Frances J. Roberts            4.58  9781593109158
3178                David A. Nadler            4.62  9781555424435
3438               Sara Barton-Wood            5.00  9780739844328
3706               Elizabeth George            4.69  9780736911689
3833            Sheri Rose Shepherd            5.00  9781590529621
3909                     Alice Wong            4.88  9780941807555
3927                 R. McL. Wilson            5.00  9780567044716
4108                Julie Sylvester            5.00  9783829602266
4415                   Jerry Burton            4.83  9780883631218
4455              Ian        Martin            5.00  9780851621814
4917                   Ross Garnaut            5.00  9780198284543
4933             William C. Dowling            5.00  9781584655800

     language_code  num_pages  ratings_count  text_reviews_count  \
63             NaN      184.0              4                   0
178            NaN      191.0              5                   0
224            eng      210.0              5                   0
454            eng       32.0              4                   1
584            eng      216.0              1                   0
681            eng      336.0              1                   1
696            eng       24.0              2                   1
741            eng      256.0              4                   0
757            eng      314.0              0                   0
1837           eng        2.0              3                   0
1856           NaN      188.0              3                   0
1960           ger      337.0              0                   0
2244           eng      124.0              9                   0
2496           eng      192.0              8                   0
3178           eng      304.0              2                   0
3438           eng       48.0              0                   0
3706           eng      160.0              9                   1
3833           eng      240.0              2                   0
3909         en-US      352.0              8                   0
3927           eng      512.0              1                   0
4108           eng       83.0              1                   0
4415           eng      320.0              6                   1
4455           eng       96.0              1                   0
4917           eng      350.0              1                   0
4933           eng      179.0              1                   1

                            publisher  year
63                                 東立  2004
178                                東立  2004
224        Teacher's Pet Publications  2005
454                Teaching Resources  2002
584                         iUniverse  2006
681                         Zondervan  2003
696                      Disney Press  2003
741                    Voyageur Press  2007
757        Texas A&M University Press  2000
1837               BBC Physical Audio  1996
1856                               東立  2005
1960                        F. Meiner  1994
2244                   Harrison House  2006
2496                    Barbour Books  2005
3178                      Jossey-Bass  1992
3438                         Raintree  2001
3706         Harvest House Publishers  2004
3833                        Multnomah  2007
3909                    Welcome Books  2001
3927                  T&T Clark Int'l  2005
4108                   Schirmer Mosel  2006
4415          Universe Publishing(NY)  2006
4455              Boosey & Hawkes Inc  2004
4917     Oxford University Press  USA  1983
4933  University Press of New England  2007

In [ ]:
eng_mean = df[df['language_code'] == 'eng']['average_rating'].mean()
print(f"The mean rating for English books is : {eng_mean}")

The mean rating for English books is : 3.931142857142857

In [ ]:
language_stats = df.groupby('language_code')['average_rating'].mean()
print(language_stats)

language_code
en-GB    3.922523
en-US    3.914800
eng      3.931143
ger      3.979773
grc      2.366667
jpn      4.252381
lat      4.170000
mul      4.116000
spa      3.927938
Name: average_rating, dtype: float64

In [ ]:
df.head(1)

,title,author,average_rating,isbn13,language_code,num_pages,ratings_count,text_reviews_count,publisher,year
0,The Hunchback of Notre-Dame,Victor Hugo,4.0,9780345472427,en-US,534.0,140,22,Modern Library,2004

In [ ]:
df.head()

,title,author,average_rating,isbn13,language_code,num_pages,ratings_count,text_reviews_count,publisher,year
0,The Hunchback of Notre-Dame,Victor Hugo,4.00,9780345472427,en-US,534.0,140,22,Modern Library,2004
1,La Cucina Di Lidia: Recipes and Memories from ...,Lidia Matticchio Bastianich,4.14,9780767914222,en-GB,288.0,48,3,Clarkson Potter,2003
2,Breach of Promise,James Scott Bell,4.00,9780310243878,eng,345.0,368,36,Zondervan,2004
3,Brief Interviews with Hideous Men,David Foster Wallace,3.86,9780349111889,eng,273.0,18335,1155,Abacus,2000
4,The Killing Dance (Anita Blake Vampire Hunter...,Laurell K. Hamilton,4.13,9780425209066,en-US,368.0,59524,946,Berkley Hardcover,2006

In [ ]:
first_five = df.iloc[0:5, 0:4]
print(first_five)

                                               title  \
0                        The Hunchback of Notre-Dame
1  La Cucina Di Lidia: Recipes and Memories from ...
2                                  Breach of Promise
3                  Brief Interviews with Hideous Men
4  The Killing Dance (Anita Blake  Vampire Hunter...

                        author  average_rating         isbn13
0                  Victor Hugo            4.00  9780345472427
1  Lidia Matticchio Bastianich            4.14  9780767914222
2             James Scott Bell            4.00  9780310243878
3         David Foster Wallace            3.86  9780349111889
4          Laurell K. Hamilton            4.13  9780425209066

In [ ]:
one_four = df.loc[[1,4],['language_code', 'num_pages', 'ratings_count']]
print(one_four)

  language_code  num_pages  ratings_count
1         en-GB      288.0             48
4         en-US      368.0          59524

In [ ]:
median_pages = df['num_pages'].median()
mean_pages = df['num_pages'].mean()
print(median_pages)
print(mean_pages)

304.0
341.0940205355345

In [ ]:
df.head()

,title,author,average_rating,isbn13,language_code,num_pages,ratings_count,text_reviews_count,publisher,year
0,The Hunchback of Notre-Dame,Victor Hugo,4.00,9780345472427,en-US,534.0,140,22,Modern Library,2004
1,La Cucina Di Lidia: Recipes and Memories from ...,Lidia Matticchio Bastianich,4.14,9780767914222,en-GB,288.0,48,3,Clarkson Potter,2003
2,Breach of Promise,James Scott Bell,4.00,9780310243878,eng,345.0,368,36,Zondervan,2004
3,Brief Interviews with Hideous Men,David Foster Wallace,3.86,9780349111889,eng,273.0,18335,1155,Abacus,2000
4,The Killing Dance (Anita Blake Vampire Hunter...,Laurell K. Hamilton,4.13,9780425209066,en-US,368.0,59524,946,Berkley Hardcover,2006

In [ ]:
count_2010 = (df['year']== 2010).sum()
print(count_2010)

15

In [ ]:
daw_authors = df[(df['publisher'] == 'DAW') & (df['average_rating'] > 4)]['author'].unique()
print(daw_authors)

['Mercedes Lackey' 'Sharon Green']

In [ ]:
count_500 = ((df['num_pages'] > 500) & (df['year'] > 2010)).sum()
print(count_500)

5

In [ ]:
Agatha_count = df['author'].str.contains('Agatha Christie',case=False,na=False).sum()
print(Agatha_count)

21

In [ ]:
spanish_count = ((df['language_code'] == 'spa') & (df['year'] > 2000)).sum()
print(spanish_count)

84